default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: test_8_development

test:
  <<: *default
  database: test_8_test

production:
  <<: *default
  database: test_8_production